In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('COVID-19.csv')
data

,Sno,age,gender,body temperature,Dry Cough,sour throat,weakness,breathing problem,drowsiness,pain in chest,...,stroke or reduced immunity,symptoms progressed,high blood pressue,kidney disease,change in appetide,Loss of sense of smell,Corona result,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,1,20,1,98.6,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,2,19,1,99.0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,3,55,0,102.0,1,1,1,1,1,1,...,0,0,0,0,1,0,1,NaN,NaN,NaN
3,4,40,0,100.0,0,0,0,0,1,1,...,0,1,1,0,1,0,2,NaN,NaN,NaN
4,5,33,1,99.2,0,1,0,1,0,0,...,1,1,0,0,0,1,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,123,37,1,102.0,1,1,1,1,0,0,...,0,1,0,0,1,0,0,NaN,NaN,NaN
123,124,35,0,100.0,0,0,0,0,1,1,...,0,0,1,0,1,0,1,NaN,NaN,NaN
124,125,22,1,99.2,0,0,0,1,0,0,...,1,1,0,0,0,1,1,NaN,NaN,NaN
125,126,29,0,102.0,0,1,1,1,1,1,...,0,0,0,0,1,1,0,NaN,NaN,NaN
126,127,38,0,101.0,1,1,0,1,1,1,...,0,1,1,0,0,0,2,NaN,NaN,NaN

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 24 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Sno                                   127 non-null    int64
 1   age                                   127 non-null    int64
 2   gender                                127 non-null    int64
 3   body temperature                      127 non-null    float64
 4   Dry Cough                             127 non-null    int64
 5   sour throat                           127 non-null    int64
 6   weakness                              127 non-null    int64
 7   breathing problem                     127 non-null    int64
 8   drowsiness                            127 non-null    int64
 9   pain in chest                         127 non-null    int64
 10  travel history to infected countries  127 non-null    int64
 11  diabetes                              127 non-null    int64
 12  heart disease                         127 non-null    int64
 13  lung disease                          127 non-null    int64
 14  stroke or reduced immunity            127 non-null    int64
 15  symptoms progressed                   127 non-null    int64
 16  high blood pressue                    127 non-null    int64
 17  kidney disease                        127 non-null    int64
 18  change in appetide                    127 non-null    int64
 19  Loss of sense of smell                127 non-null    int64
 20  Corona result                         127 non-null    int64
 21  Unnamed: 21                           0 non-null      float64
 22  Unnamed: 22                           0 non-null      float64
 23  Unnamed: 23                           0 non-null      float64
dtypes: float64(4), int64(20)
memory usage: 23.9 KB

In [4]:
data_df = pd.DataFrame(data,columns=['age','gender','body temperature','weakness','breathing problem','drowsiness','pain in chest','stroke or reduced immunity','diabetes','high blood pressue','Loss of sense of smell','Corona result'])
data_df

,age,gender,body temperature,weakness,breathing problem,drowsiness,pain in chest,stroke or reduced immunity,diabetes,high blood pressue,Loss of sense of smell,Corona result
0,20,1,98.6,0,0,0,0,0,0,0,0,0
1,19,1,99.0,0,0,0,0,0,0,0,0,0
2,55,0,102.0,1,1,1,1,0,0,0,0,1
3,40,0,100.0,0,0,1,1,0,1,1,0,2
4,33,1,99.2,0,1,0,0,1,0,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
122,37,1,102.0,1,1,0,0,0,0,0,0,0
123,35,0,100.0,0,0,1,1,0,1,1,0,1
124,22,1,99.2,0,1,0,0,1,0,0,1,1
125,29,0,102.0,1,1,1,1,0,0,0,1,0
126,38,0,101.0,0,1,1,1,0,1,1,0,2

In [5]:
from sklearn.linear_model import LogisticRegression

In [6]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [7]:
train, test = data_split(data_df, 0.2)

In [8]:
train

,age,gender,body temperature,weakness,breathing problem,drowsiness,pain in chest,stroke or reduced immunity,diabetes,high blood pressue,Loss of sense of smell,Corona result
78,33,0,97.9,1,0,0,0,0,0,1,0,0
68,23,1,99.3,1,1,0,0,0,0,1,1,1
69,21,0,98.4,1,1,1,1,0,0,0,0,1
12,58,0,99.6,0,1,0,1,1,0,0,1,0
42,30,1,102.1,1,0,1,0,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
106,19,1,102.4,0,1,1,0,0,0,0,0,1
14,60,1,96.0,0,0,0,0,1,1,1,0,0
92,42,0,99.3,1,1,0,1,0,0,0,0,1
51,24,1,98.6,1,0,1,0,0,0,0,1,1
102,39,1,100.1,0,1,1,1,0,0,0,0,1

In [9]:
test

,age,gender,body temperature,weakness,breathing problem,drowsiness,pain in chest,stroke or reduced immunity,diabetes,high blood pressue,Loss of sense of smell,Corona result
26,37,1,99.0,1,1,0,0,0,0,1,1,1
111,24,0,100.4,0,0,0,1,0,0,0,1,1
81,31,1,101.1,1,1,0,1,0,0,1,1,1
55,20,1,102.2,0,1,0,1,0,0,0,1,2
44,24,1,102.3,1,0,1,0,0,0,0,0,1
96,31,0,101.1,0,0,0,0,0,0,0,0,0
80,22,1,102.4,0,1,1,0,0,0,0,1,1
125,29,0,102.0,1,1,1,1,0,0,0,1,0
114,46,0,100.1,1,0,1,0,1,0,0,0,1
62,40,0,100.0,0,0,1,1,0,0,1,0,1
45,37,0,99.0,1,1,0,0,0,1,1,1,2
4,33,1,99.2,0,1,0,0,1,0,0,1,2
18,64,1,102.0,1,0,0,0,0,0,0,0,1
95,46,1,102.4,0,0,0,0,0,0,0,0,0
36,20,0,102.2,0,1,0,1,0,0,1,1,1
94,29,1,98.6,0,0,0,0,0,0,1,1,0
19,65,0,99.0,0,0,0,0,1,1,1,0,2
120,19,0,98.6,1,0,0,0,0,0,0,0,0
10,56,1,100.0,0,0,0,0,0,0,0,0,0
40,67,0,99.0,0,0,0,0,0,0,0,0,0
11,57,0,100.0,1,0,0,1,0,0,0,0,1
98,46,1,100.0,0,0,1,1,1,0,0,0,1
104,33,0,97.9,0,0,0,0,0,0,0,0,0
77,25,1,102.1,0,0,1,0,0,0,0,1,1
0,20,1,98.6,0,0,0,0,0,0,0,0,0

In [10]:
X_train = train[['age','gender','body temperature','weakness','breathing problem','drowsiness','pain in chest','stroke or reduced immunity','diabetes','high blood pressue','Loss of sense of smell']].to_numpy()
X_test = test[['age','gender','body temperature','weakness','breathing problem','drowsiness','pain in chest','stroke or reduced immunity','diabetes','high blood pressue','Loss of sense of smell']].to_numpy()

Y_train = train[['Corona result']].to_numpy().ravel()
Y_test = test[['Corona result']].to_numpy().ravel()

In [11]:
model = LogisticRegression()

In [12]:
import pickle
model.fit(X_train,Y_train)
pickle.dump(model, open("model2.pkl", 'wb'))

C:\Users\Raksha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [14]:
inputFeatures = [45,1,100,1,1,1,1,1,1,1,1]
loaded_model = pickle.load(open("model2.pkl", 'rb'))
infProb =loaded_model.predict([inputFeatures])
if infProb == 0:
  print("No Severity")
elif infProb == 1:
  print("Mild Severity")
elif infProb == 2:
  print("High Severity")

Mild Severity

In [15]:
accuracy = model.score(X_test,Y_test)
accuracy

0.68